production:
  solr:
    hostname: localhost
    port: 8080
    log_level: WARNING

development:
  solr:
    hostname: search
    port: 8983
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8080
    log_level: WARNING
